#%RAML 1.0 NamedExample
value:
    Region: Europe
    price: 800
    productName: ipad
    shippingAddress: shipping address germany
    quantity: 1
    orderDate: 2020/10/11
    Country:
      countryName: germany
      currency: pound
